version: '3'

services:
  grpc-server:
    build:
      context: ./
      dockerfile: ./docker/grpc_server/Dockerfile
    deploy:
      replicas: 1
    image: grpc-server
    volumes:
      - ./testdata:/grpc_with_envoy/testdata:ro
    networks:
      - overlay
    ports:
      - "9090:9090"

  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    image: envoy
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - overlay
    links:
      - grpc-server
    ports:
      - "8080:8080"
      - "9901:9901"

networks:
  overlay:
