version: '3'

services:
  grpc-server:
    build:
      context: ./
      dockerfile: ./docker/grpc_server/Dockerfile
    deploy:
      replicas: 1
    image: npuichigo/grpc-server
    volumes:
      - ./testdata:/grpc_with_envoy/testdata:ro
    networks:
      - overlay
    ports:
      - "9090:9090"

  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    image: npuichigo/envoy
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "debug"]
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    networks:
      - overlay
    links:
      - grpc-server
    ports:
      - "8080:8080"
      - "9901:9901"

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    image: npuichigo/nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - overlay
    links:
      - envoy
    ports:
      - "80:80"

networks:
  overlay:
